## 에러 처리 문법
### 에러(오류)의 이해
---
 - 에러의 종류는
   1) 컴파일 타임 에러 ===> 스위프트 문법과 관련된 에러(컴파일러가 미리 알고 수정해야한다고 알려줌)
   2) 런타임 에러 ===> 프로그램이 실행되는 동안 발생

 - 런타임 에러 ===> 크래시(앱이 강제로 종료)
   ===> 발생가능한 에러를 미리 처리해 두면, 강제종료되지 않음 (개발자가 처리해야만 하는 에러)

---
### (런타임)에러 처리가 왜 필요할까?
---
 - 앱이 실행하는 중간에 왜 꺼질까?
 
 - 어떤 얘기치 못한 상황이 발생할 수 있음
 - (네트워크 통신을 하는 등의 경우에서) 서버에서 데이터를 못 받아와서 ==> 꺼짐

 - 앱이 그냥 꺼지는 게 좋은가? 아니면 예를들어 "서버에서 문제가 발생했습니다. 잠시뒤에 다시 접속해 주세요"라고
   알려주는 것이 좋은 가?
 
 - 프로세스 중에서, 예외적인 상황(에러)이 발생하는 것이 미리 가능성 등을 처리해 놓으면
   앱이 무작정 꺼지는 것을 예방할 수 있음 ⭐️


 - 에러는 일반적으로 동작. 즉, 함수의 처리과정에서 일어남
 - 함수를 정의할때, 예외적인 일이 발생하는 경우가 발생할 수 있는 함수이다.라고 정의하고 처리하는 과정을 배울 것임


 - (에러 발생 가능)함수 ====>  함수 실행시에 조금 다르게 처리해야함(에러 처리) ⭐️

---
### 에러 처리의 과정 (3단계)
```javascript
// 1) 에러 정의 (어떤 에러가 발생할지 경우를 미리 정의)

enum HeightError: Error {    //에러 프로토콜 채택 (약속)
    case maxHeight
    case minHeight
}




// 2) 에러가 발생할 수 있는 함수에 대한 정의

func checkingHeight(height: Int) throws -> Bool {    // (에러를 던잘수 있는 함수 타입이다)
    
    if height > 190 {
        throw HeightError.maxHeight
    } else if height < 130 {
        throw HeightError.minHeight
    } else {
        if height >= 160 {
            return true
        } else {
            return false
        }
    }
}




// 3) 에러가 발생할 수 있는 함수의 처리(함수의 실행) ===> 기존과 조금 다르다 (try와 do-catch문으로 처리)


do {
    
    let isChecked = try checkingHeight(height: 200)
    print("놀이기구 타는 것 가능: \(isChecked)")
    
} catch {
    
    print("놀이기구 타는 것 불가능")
    
}

/**================================================
 - do블럭  - 함수를 통한 정상적인 처리의 경우 실행하는 블럭
 - catch블럭 - 함수가 에러를 던졌을 경우의 처리 실행하는 블럭
 ==================================================**/
```
### 에러 발생가능한 함수의 형태
```javascript
=========================
 - () throws -> ()
 - (Int) throws -> ()
=========================


//[1, 2, 3, 4, 5].map(transform: (Int) throws -> T)
```
## Reference
[Inflearn - 앨런 swift 문법 마스터 스쿨](https://www.inflearn.com/course/%EC%8A%A4%EC%9C%84%ED%94%84%ED%8A%B8-%EB%AC%B8%EB%B2%95-%EB%A7%88%EC%8A%A4%ED%84%B0-%EC%8A%A4%EC%BF%A8/dashboard)
